### ISSUE TITLE
Sound lag

### ISSUE THREAD

**Issue by dosboxonline** [gamejolt/retrojolt#4]
Sound lag(delay) all drivers and browsers. Or it's a question for the MAME developers? Thanks

**Comment by hworld** [comment]
Hmm, it may be this project. You can test in MAME for desktop to see if there is lag or delay. One of the big issues is that browser audio isn't the best. Low latency can be tricky.

This project uses Emularity to do most of the embedding, which in turn just embeds MAME into the browser which does the majority of the work. It looks like Emularity may have done some stuff to audio since I last pulled from them here: https://github.com/db48x/emularity/commit/03c4d4e3a79c600447bd2399375d565a288eba8a

I could possibly try to see if this fixes the issues. Would just be a matter of updating the vendor commit that this project tracks and rebuilding the JS.

**Comment by dosboxonline** [comment]
I compared with Sega on archive.org and retrojult -https://dosboxonline.github.io/games90s/genesis/alien-3.html Thanks for answer.

**Comment by hworld** [comment]
Is the archive.org sound better?

**Comment by dosboxonline** [comment]
On archive.org sound Ok all consoles.

**Comment by dosboxonline** [comment]
We will not look for a solution to the problem. I remembered that the Emularity problem is similar.

**Comment by dosboxonline** [comment]
Emularity repo - https://dosboxonline.github.io/games90s/segams/ninja-gaiden.html Sound lag

**Comment by dosboxonline** [comment]
Emularity after same question - "I've not noticed any audio lag myself. Audio emulation is generally quite CPU-intensive, though, so it may happen on slower computers."
